
using Helpers;

namespace BO;
public class Courier
{
    // 1. Courier ID 
    /// <summary>
    /// The unique identifier for the Courier. Read-only.
    /// Integrity check is performed in the logical layer upon creation.
    /// </summary>
    public int Id { get; init; }

    // 2. Full Name 
    /// <summary>
    /// The courier's full name (first and last). Updatable by manager or courier.
    /// </summary>
    public string NameCourier { get; set; }

    // 3. Mobile Phone
    /// <summary>
    /// The courier's mobile phone number. Updatable by manager or courier.
    /// Integrity check is performed in the logical layer.
    /// </summary>
    public string PhoneNumber { get; set; }

    /// <summary>
    /// The courier's email address. Updatable by manager or courier.
    /// Integrity check is performed in the logical layer.
    /// </summary>
    public string EmailCourier { get; set; }

    // 5. Password 
    /// <summary>
    /// The courier's password (for login). Updatable by manager or courier.
    /// Integrity check is performed in the logical layer.
    /// </summary>
    public string PasswordCourier { get; set; }

    // 6. Active Status 
    /// <summary>
    /// Indicates whether the courier is currently active. Updatable by manager ONLY.
    /// Integrity check is performed in the logical layer.
    /// </summary>
    public bool IsActive { get; set; }

    // 7. Maximum Personal Delivery Distance 
    /// <summary>
    /// The maximum distance the courier is willing to travel for a delivery.
    /// Nullable. Updatable by manager or courier.
    /// Integrity check is performed in the logical layer.
    /// </summary>
    public double? PersonalMaxAirDistance { get; set; }

    // 8. Shipping Type 
    /// <summary>
    /// The type of deliveries the courier can handle. Updatable by manager or courier.
    /// </summary>
    public DeliveryTypeMethods DeliveryType { get; set; }

    // 9. Start Date 
    /// <summary>
    /// The date and time the courier started working for the company. Read-only.
    /// Generated by the data layer upon creation.
    /// </summary>
    public DateTime StartDate { get; init; }

    // 10. Total Orders Delivered On Time 
    /// <summary>
    /// The total number of orders delivered on time. Read-only.
    /// Calculated in the logical layer based on historical data.
    /// </summary>
    public int TotalDeliveredOnTime { get; init; }

    // 11. Total Late Deliveries 
    /// <summary>
    /// The total number of orders delivered late. Read-only.
    /// Calculated in the logical layer based on historical data.
    /// </summary>
    public int TotalLateDeliveries { get; init; }

    // 12. Order In Progress 
    /// <summary>
    /// The order the courier is currently handling. Nullable. Read-only.
    /// Retrieved from the logical layer (BO.OrderInProgress) via a query.
    /// Null if the courier is not currently handling any order.
    /// </summary>
    public OrderInProgress? OrderInProgress { get; init; }

    /// <summary>
    /// 13.salary details for the courier. Nullable-if courier is not active it will be null. adddeed for salary calculation
    /// </summary>
    public SalaryForCourier? SalaryForCourier { get; set; }
    public override string ToString() => Tools.ToStringProperty<Courier>(this);

}
