
using Helpers;

namespace BO;

public class Order
{
    // 1. Order ID 
    /// <summary>
    /// The unique, running identifier for the Order entity. Read-only.
    /// Generated by the data layer upon creation.
    /// </summary>
    public int Id { get; init; }

    // 2. Order Type 
    /// <summary>
    /// The type of order. Updatable by manager.
    /// Integrity check is performed in the logical layer.
    /// </summary>
    public OrderRequirements OrderType { get; set; }

    // 3. Description 
    /// <summary>
    /// Verbal description of the order content. Nullable. Updatable by manager.
    /// </summary>
    public string? ShortOrderDescription { get; set; }

    // 4. Full Address 
    /// <summary>
    /// The full, valid, and real address of the order location. Updatable by manager.
    /// The logical layer calculates Latitude/Longitude and validates the address existence.
    /// </summary>
    public string FullAddress { get; set; }

    // 5. Latitude 
    /// <summary>
    /// The latitude of the order's location. Read-only in display (not shown).
    /// Automatically updated by the logical layer upon address change.
    /// </summary>
    public double Latitude { get; set; }

    // 6. Longitude 
    /// <summary>
    /// The longitude of the order's location. Read-only in display (not shown).
    /// Automatically updated by the logical layer upon address change.
    /// </summary>
    public double Longitude { get; set; }

    // 7. Air Distance 
    /// <summary>
    /// The straight-line (air) distance from the company's location. Read-only.
    /// Automatically calculated by the logical layer upon address change.
    /// </summary>
    public double AirDistance { get; set; }

    // 8. Customer Full Name 
    /// <summary>
    /// The full name of the customer placing the order. Updatable by manager.
    /// </summary>
    public string CustomerFullName { get; set; } 

    // 9. Customer Phone 
    /// <summary>
    /// The phone number of the customer. Updatable by manager.
    /// Integrity check is performed in the logical layer.
    /// </summary>
    public string CustomerPhone { get; set; }

    // 10. Item Attributes  - Example of required attributes
    /// <summary>
    /// Attributes of the item, FreeShippingEligibility, AmountItems ,Updatable by manager.
    /// </summary>
    public bool FreeShippingEligibility { get; set; }
    public int AmountItems { get; set; }


    // 11. Order Opening Time
    /// <summary>
    /// The date and time the order was opened. Read-only.
    /// Retrieved from the data layer.
    /// </summary>
    public DateTime OrderOpeningTime { get; init; }

    // 12. Estimated Delivery Time 
    /// <summary>
    /// The expected delivery date and time, calculated by the logical layer
    /// based on current delivery start time, order distance, and courier speed/type. Read-only.
    /// </summary>
    public DateTime? ExpectedDeliveryTime { get; init; }

    //13. Maximum Delivery Time 
    /// <summary>
    /// The maximum delivery date and time guaranteed by the company, based on
    /// the order's opening time and company policy (Config). Read-only.
    /// Calculated in the logical layer.
    /// </summary>
    public DateTime MaximumDeliveryTime { get; init; }

    // 14. Order Status 
    /// <summary>
    /// The overall status of the order, calculated by the logical layer based on the
    /// latest delivery status. Read-only.
    /// </summary>
    public OrderStatus OrderStatus { get; init; }

    // 15. Schedule Status 
    /// <summary>
    /// The status regarding adherence to deadlines (e.g., OnTime, Delayed),
    /// calculated by the logical layer based on the latest delivery and configuration. Read-only.
    /// </summary>
    public ScheduleStatus ScheduleStatus { get; init; }

    // 16. Time Remaining 
    /// <summary>
    /// The total remaining time to complete the order (MaximumDeliveryTime minus current time).
    /// If the order is closed, the value is 00:00:00. Read-only.
    /// </summary>
    public TimeSpan TimeRemaining { get; init; }

    // 17. Delivery History 
    /// <summary>
    /// A list of previous and current deliveries associated with the order. Nullable if no deliveries exist. Read-only.
    /// Retrieved by the logical layer.
    /// </summary>
    public List<DeliveryPerOrderInList>? DeliveryHistory { get; init; }
    public override string ToString() => Tools.ToStringProperty<Order>(this);

}